name: Publish on release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tinetti'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
      - name: Build
        run: pnpm run build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm publish --no-git-checks --access public
